
redis:
    build: ./redis
    ports:
        - "6379:6379"
 
nginx:
    build: ./nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/html:/usr/share/nginx/html
        
